import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { VideoBackground } from "@/components/ui/VideoBackground";
import { useQuiz, useSubmitQuiz, useQuizLeaderboard } from "@/hooks/usePlayerData";
import type { QuizData, QuizResult } from "@/lib/api";

type QuizPhase = "intro" | "loading" | "playing" | "result" | "leaderboard" | "error";

function QuizIntro({ onStart }: { onStart: () => void }) {
  return (
    <motion.div
      className="flex flex-col items-center justify-center min-h-[70vh] text-center px-4"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95 }}
    >
      <div className="text-[10px] sm:text-xs text-[#c0392b] tracking-[0.3em] uppercase mb-3 sm:mb-4 font-bold">
        The Ultimate Test
      </div>
      <h1
        className="font-serif text-4xl sm:text-5xl md:text-7xl text-white mb-4 sm:mb-6 leading-tight"
        style={{ textShadow: "0 4px 30px rgba(0,0,0,0.8)" }}
      >
        KOHLI FANBOY QUIZ
      </h1>
      <p className="text-[#a0a0a0] max-w-md mx-auto mb-8 sm:mb-10 text-xs sm:text-sm px-2">
        10 fresh questions generated by AI. Only one correct answer.
        Prove your loyalty to the King.
      </p>
      <button
        onClick={onStart}
        className="px-8 sm:px-12 py-3.5 sm:py-4 text-xs sm:text-sm font-bold tracking-[0.2em] uppercase bg-[#c0392b] text-white hover:bg-[#a93226] transition-all hover:scale-105 active:scale-95 shadow-[0_0_20px_rgba(192,57,43,0.4)]"
      >
        Enter the Arena
      </button>
      <div className="mt-8 text-[10px] text-[#555] tracking-widest uppercase">
        Powered by Gemini · Takes ~2 min
      </div>
    </motion.div>
  );
}

function LoadingState({ message }: { message: string }) {
  return (
    <div className="flex flex-col items-center justify-center min-h-[60vh] text-center">
      <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-full border-2 border-[#c0392b] border-t-transparent animate-spin mb-4 sm:mb-6" />
      <div className="text-[10px] sm:text-xs text-[#c0392b] tracking-[0.2em] uppercase font-bold animate-pulse">
        {message}
      </div>
    </div>
  );
}

function ErrorState({ error, onRetry }: { error: any; onRetry: () => void }) {
  const isBudget = error?.message?.includes("budget") || error?.name === "BudgetExceededError";
  return (
    <div className="flex flex-col items-center justify-center min-h-[60vh] text-center px-4">
      <div className="text-red-500 mb-4 text-4xl">⚠️</div>
      <h2 className="text-xl sm:text-2xl text-white mb-2 font-serif">
        {isBudget ? "Quiz Generator Paused" : "Arena Unavailable"}
      </h2>
      <p className="text-[#888] text-xs sm:text-sm mb-6 max-w-sm">
        {isBudget
          ? "The API quota is exhausted. Please come back tomorrow."
          : "The quiz generator is having trouble. Make sure GEMINI_API_KEY is configured on the server."}
      </p>
      <button
        onClick={onRetry}
        className="px-6 py-2 border border-white/20 text-xs uppercase tracking-widest hover:bg-white/10"
      >
        Try Again
      </button>
    </div>
  );
}

function QuizPlay({
  quizData,
  onComplete,
}: {
  quizData: QuizData;
  onComplete: (result: QuizResult) => void;
}) {
  const [currentIdx, setCurrentIdx] = useState(0);
  const [answers, setAnswers] = useState<{ questionId: string; selectedIndex: number }[]>([]);
  const [lockedIn, setLockedIn] = useState<number | null>(null);

  const submitMutation = useSubmitQuiz();
  const q = quizData.questions[currentIdx];
  const total = quizData.questions.length;

  const handleSelect = (idx: number) => {
    if (lockedIn !== null) return;
    setLockedIn(idx);

    const newAnswers = [...answers, { questionId: q.id, selectedIndex: idx }];
    setAnswers(newAnswers);

    setTimeout(() => {
      if (currentIdx < total - 1) {
        setLockedIn(null);
        setCurrentIdx((c) => c + 1);
      } else {
        submitMutation.mutate(
          { token: quizData.quizToken, answers: newAnswers },
          {
            onSuccess: (data: QuizResult) => onComplete(data),
            onError: () => {
              // Allow user to retry by unlocking selection
              setLockedIn(null);
            },
          }
        );
      }
    }, 900);
  };

  if (submitMutation.isPending) {
    return <LoadingState message="Scoring Quiz..." />;
  }

  if (submitMutation.isError) {
    return (
      <ErrorState
        error={submitMutation.error}
        onRetry={() => submitMutation.mutate({ token: quizData.quizToken, answers })}
      />
    );
  }

  const progress = (currentIdx / total) * 100;

  return (
    <div className="max-w-3xl mx-auto w-full pt-4 sm:pt-10 px-2 sm:px-0">
      {/* Progress Bar */}
      <div className="mb-6 sm:mb-10">
        <div className="flex justify-between text-[10px] sm:text-xs uppercase tracking-widest text-[#666] mb-2">
          <span>
            Q{currentIdx + 1}/{total}
          </span>
          <span>{Math.round(progress)}%</span>
        </div>
        <div className="h-1 bg-white/10 w-full overflow-hidden">
          <motion.div
            className="h-full bg-[#c0392b]"
            initial={{ width: 0 }}
            animate={{ width: `${progress}%` }}
            transition={{ duration: 0.5 }}
          />
        </div>
      </div>

      <AnimatePresence mode="wait">
        <motion.div
          key={q.id}
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: -20 }}
          className="bg-[#080808]/85 backdrop-blur-md p-5 sm:p-8 md:p-12 border border-white/10"
        >
          <div className="text-[10px] uppercase tracking-[0.2em] text-[#c0392b] mb-2 sm:mb-3 font-bold">
            Question {currentIdx + 1}
          </div>
          <h2 className="font-serif text-xl sm:text-2xl md:text-3xl text-white mb-6 sm:mb-8 leading-snug">
            {q.question}
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 sm:gap-4">
            {q.options.map((opt, i) => {
              const isSelected = lockedIn === i;
              const isLocked = lockedIn !== null;

              return (
                <button
                  key={i}
                  onClick={() => handleSelect(i)}
                  disabled={isLocked}
                  className={`
                    text-left p-3.5 sm:p-4 md:p-6 border transition-all duration-300 min-h-[60px]
                    ${
                      isSelected
                        ? "bg-[#c0392b] border-[#c0392b] text-white shadow-[0_0_15px_rgba(192,57,43,0.5)]"
                        : "bg-transparent border-white/10 text-[#d0d0d0] hover:border-white/30 hover:bg-white/5 active:bg-white/10"
                    }
                    ${isLocked && !isSelected ? "opacity-30 grayscale" : ""}
                  `}
                >
                  <div className="flex items-start gap-3 sm:gap-4">
                    <span
                      className={`text-[10px] sm:text-xs font-mono mt-0.5 sm:mt-1 shrink-0 ${
                        isSelected ? "text-white/80" : "text-[#c0392b]"
                      }`}
                    >
                      {String.fromCharCode(65 + i)}
                    </span>
                    <span className="text-sm sm:text-base leading-tight font-medium">
                      {opt}
                    </span>
                  </div>
                </button>
              );
            })}
          </div>
        </motion.div>
      </AnimatePresence>
    </div>
  );
}

function QuizResultView({
  result,
  quizData,
  onPlayAgain,
  onViewLeaderboard,
}: {
  result: QuizResult;
  quizData: QuizData | null;
  onPlayAgain: () => void;
  onViewLeaderboard: () => void;
}) {
  return (
    <motion.div
      className="max-w-2xl mx-auto text-center py-6 sm:py-10 px-2"
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
    >
      <div className="text-[10px] sm:text-xs text-[#888] tracking-[0.2em] uppercase mb-3 sm:mb-4">
        Quiz Completed
      </div>

      <div className="text-6xl sm:text-7xl mb-4 sm:mb-6">{result.tierEmoji}</div>

      <div
        className="font-serif text-5xl sm:text-6xl md:text-7xl text-[#d4a500] mb-2 font-bold"
        style={{ textShadow: "0 0 30px rgba(212,165,0,0.3)" }}
      >
        {result.percentage}%
      </div>

      <div className="text-xl sm:text-2xl text-white font-medium mb-1 px-2">{result.tier}</div>
      <div className="text-[#666] text-xs sm:text-sm mb-8 sm:mb-12">
        You scored {result.totalScore} out of {result.maxScore} points.
      </div>

      <div className="flex flex-col sm:flex-row items-center justify-center gap-3 sm:gap-4">
        <button
          onClick={onPlayAgain}
          className="w-full sm:w-auto px-8 py-3.5 sm:py-4 text-xs sm:text-sm font-bold tracking-[0.15em] uppercase bg-[#c0392b] text-white hover:bg-[#a93226] transition-colors"
        >
          Play Again
        </button>
        <button
          onClick={onViewLeaderboard}
          className="w-full sm:w-auto px-8 py-3.5 sm:py-4 text-xs sm:text-sm font-bold tracking-[0.15em] uppercase border border-white/20 text-white hover:bg-white/10 transition-colors"
        >
          Leaderboard
        </button>
      </div>

      {/* Breakdown — show what was right & the question text */}
      {quizData && (
        <div className="mt-12 sm:mt-16 text-left">
          <h3 className="font-serif text-lg sm:text-xl text-white mb-4 sm:mb-6 border-b border-white/10 pb-2">
            Match Report
          </h3>
          <div className="space-y-3 sm:space-y-4">
            {result.breakdown.map((b, i) => {
              const question = quizData.questions.find((q) => q.id === b.questionId);
              return (
                <div
                  key={b.questionId}
                  className={`p-3 sm:p-4 border ${
                    b.correct
                      ? "border-green-500/20 bg-green-500/5"
                      : "border-red-500/20 bg-red-500/5"
                  }`}
                >
                  <div className="flex justify-between items-start gap-3 mb-2">
                    <span className="text-[9px] sm:text-[10px] uppercase tracking-wider text-[#666] shrink-0">
                      Q{i + 1}
                    </span>
                    <span
                      className={`text-[10px] font-bold uppercase tracking-wider shrink-0 ${
                        b.correct ? "text-green-500" : "text-red-500"
                      }`}
                    >
                      {b.correct ? "✓ +10" : "✗ 0"}
                    </span>
                  </div>
                  {question && (
                    <div className="text-xs sm:text-sm text-[#d0d0d0] leading-snug">
                      {question.question}
                    </div>
                  )}
                  {question && b.selectedIndex >= 0 && (
                    <div className="mt-1.5 text-[10px] sm:text-xs text-[#888]">
                      Your answer:{" "}
                      <span className={b.correct ? "text-green-400" : "text-red-400"}>
                        {question.options[b.selectedIndex]}
                      </span>
                    </div>
                  )}
                  {question && !b.correct && (
                    <div className="mt-1 text-[10px] sm:text-xs text-[#888]">
                      Correct:{" "}
                      <span className="text-green-400">{question.options[b.correctIndex]}</span>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </motion.div>
  );
}

function LeaderboardView({
  onClose,
}: {
  onClose: () => void;
}) {
  const { data, isLoading, error } = useQuizLeaderboard();

  return (
    <motion.div
      className="max-w-2xl mx-auto text-center py-6 sm:py-10 px-2"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
    >
      <div className="text-[10px] sm:text-xs text-[#888] tracking-[0.2em] uppercase mb-3 sm:mb-4">
        Top 20 Chikoos
      </div>
      <h2 className="font-serif text-3xl sm:text-4xl md:text-5xl text-white mb-8 sm:mb-12">
        LEADERBOARD
      </h2>

      {isLoading && <LoadingState message="Loading Chikoos..." />}

      {error && (
        <div className="text-[#888] text-sm">
          Could not load the leaderboard. Try again later.
        </div>
      )}

      {data && data.length === 0 && (
        <div className="text-[#888] text-sm py-12">
          No one has played yet. Be the first to claim the throne.
        </div>
      )}

      {data && data.length > 0 && (
        <div className="text-left space-y-2 sm:space-y-3">
          {data.map((entry, i) => (
            <div
              key={`${entry.user_id ?? "anon"}-${entry.created_at}-${i}`}
              className="flex items-center justify-between p-3 sm:p-4 border border-white/10 bg-[#080808]/60 backdrop-blur-sm"
            >
              <div className="flex items-center gap-3 sm:gap-4 min-w-0">
                <div
                  className={`text-base sm:text-lg font-bold w-6 sm:w-8 shrink-0 ${
                    i === 0
                      ? "text-[#d4a500]"
                      : i === 1
                      ? "text-[#c0c0c0]"
                      : i === 2
                      ? "text-[#cd7f32]"
                      : "text-[#666]"
                  }`}
                >
                  #{i + 1}
                </div>
                <div className="min-w-0">
                  <div className="text-xs sm:text-sm text-white truncate">
                    {entry.user_id ? entry.user_id : "Anonymous Chikoo"}
                  </div>
                  <div className="text-[9px] sm:text-[10px] text-[#666] uppercase tracking-wider">
                    {entry.tier}
                  </div>
                </div>
              </div>
              <div className="text-right shrink-0">
                <div className="text-base sm:text-lg font-bold text-[#d4a500]">
                  {entry.percentage}%
                </div>
                <div className="text-[9px] sm:text-[10px] text-[#666]">
                  {entry.score}/{entry.max_score}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      <button
        onClick={onClose}
        className="mt-8 sm:mt-12 w-full sm:w-auto px-8 py-3.5 sm:py-4 text-xs sm:text-sm font-bold tracking-[0.15em] uppercase border border-white/20 text-white hover:bg-white/10 transition-colors"
      >
        Back to Quiz
      </button>
    </motion.div>
  );
}

export default function Quiz() {
  const [phase, setPhase] = useState<QuizPhase>("intro");
  const [result, setResult] = useState<QuizResult | null>(null);
  const [lastQuiz, setLastQuiz] = useState<QuizData | null>(null);
  const errorShownRef = useRef(false);

  // Lazy hook — enabled only after the user clicks "Enter the Arena"
  const { data: quizData, isLoading, error, refetch, isFetching } = useQuiz();

  // When the lazy query resolves, transition into the playing phase
  useEffect(() => {
    if (isLoading || isFetching) return;
    if (error) {
      if (!errorShownRef.current) {
        setPhase("error");
        errorShownRef.current = true;
      }
      return;
    }
    if (quizData && phase === "loading" && !errorShownRef.current) {
      setLastQuiz(quizData);
      setPhase("playing");
    }
  }, [quizData, isLoading, isFetching, error, phase]);

  const handleStart = () => {
    setPhase("loading");
    setResult(null);
    errorShownRef.current = false;
    if (quizData && !isFetching) {
      // Already have a quiz — use it without re-fetching
      setLastQuiz(quizData);
      setPhase("playing");
    } else {
      refetch();
    }
  };

  const handleComplete = (res: QuizResult) => {
    setResult(res);
    setPhase("result");
  };

  const handlePlayAgain = () => {
    setResult(null);
    setPhase("loading");
    errorShownRef.current = false;
    refetch();
  };

  const handleRetry = () => {
    setPhase("loading");
    errorShownRef.current = false;
    refetch();
  };

  return (
    <div className="relative min-h-[calc(100vh-52px)] px-3 sm:px-6 md:px-8 pb-16 sm:pb-20">
      <VideoBackground
        src="/stadium-floodlight.mp4"
        opacity={0.55}
        overlayOpacity={0.45}
        className="fixed"
      />
      <div className="absolute inset-0 z-0 bg-gradient-to-b from-transparent via-[#050505]/70 to-[#050505] pointer-events-none fixed" />

      <div className="relative z-10 w-full h-full pt-6 sm:pt-10">
        <AnimatePresence mode="wait">
          {phase === "intro" && (
            <div key="intro-row" className="space-y-4">
              <QuizIntro key="intro" onStart={handleStart} />
              <div className="text-center -mt-4 sm:mt-0">
                <button
                  onClick={() => setPhase("leaderboard")}
                  className="text-[10px] sm:text-xs text-[#888] uppercase tracking-[0.2em] hover:text-white transition-colors underline underline-offset-4"
                >
                  View Leaderboard
                </button>
              </div>
            </div>
          )}

          {phase === "loading" && <LoadingState key="loading" message="Generating Questions..." />}

          {phase === "error" && error && (
            <ErrorState key="error" error={error} onRetry={handleRetry} />
          )}

          {phase === "playing" && quizData && (
            <QuizPlay key="playing" quizData={quizData} onComplete={handleComplete} />
          )}

          {phase === "result" && result && (
            <QuizResultView
              key="result"
              result={result}
              quizData={lastQuiz}
              onPlayAgain={handlePlayAgain}
              onViewLeaderboard={() => setPhase("leaderboard")}
            />
          )}

          {phase === "leaderboard" && (
            <LeaderboardView key="leaderboard" onClose={() => setPhase("intro")} />
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
