import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { VideoBackground } from "@/components/ui/VideoBackground";
import { useQuiz, useSubmitQuiz, useQuizLeaderboard } from "@/hooks/usePlayerData";
import type { QuizResult } from "@/lib/api";

type QuizPhase = "intro" | "playing" | "result" | "leaderboard";

function QuizIntro({ onStart }: { onStart: () => void }) {
  return (
    <motion.div
      className="flex flex-col items-center justify-center min-h-[70vh] text-center"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95 }}
    >
      <div className="text-[10px] text-[#c0392b] tracking-[0.3em] uppercase mb-4 font-bold">
        The Ultimate Test
      </div>
      <h1 className="font-serif text-5xl md:text-7xl text-white mb-6" style={{ textShadow: "0 4px 30px rgba(0,0,0,0.8)" }}>
        KOHLI FANBOY QUIZ
      </h1>
      <p className="text-[#a0a0a0] max-w-md mx-auto mb-10 text-sm">
        10 fresh questions generated by AI. Only one correct answer.
        Prove your loyalty to the King.
      </p>
      <button
        onClick={onStart}
        className="px-12 py-4 text-sm font-bold tracking-[0.2em] uppercase bg-[#c0392b] text-white hover:bg-[#a93226] transition-all hover:scale-105 active:scale-95 shadow-[0_0_20px_rgba(192,57,43,0.4)]"
      >
        Enter the Arena
      </button>
    </motion.div>
  );
}

function QuizPlay({
  quizData,
  onComplete,
}: {
  quizData: any;
  onComplete: (result: QuizResult) => void;
}) {
  const [currentIdx, setCurrentIdx] = useState(0);
  const [answers, setAnswers] = useState<{ questionId: string; selectedIndex: number }[]>([]);
  const [lockedIn, setLockedIn] = useState<number | null>(null);
  
  const submitMutation = useSubmitQuiz();
  const q = quizData.questions[currentIdx];

  const handleSelect = (idx: number) => {
    if (lockedIn !== null) return;
    setLockedIn(idx);

    const newAnswers = [...answers, { questionId: q.id, selectedIndex: idx }];
    setAnswers(newAnswers);

    setTimeout(() => {
      if (currentIdx < quizData.questions.length - 1) {
        setLockedIn(null);
        setCurrentIdx(c => c + 1);
      } else {
        submitMutation.mutate(
          { token: quizData.quizToken, answers: newAnswers },
          {
            onSuccess: (data: QuizResult) => onComplete(data),
          }
        );
      }
    }, 1500); // Wait 1.5s to show selection before moving on
  };

  if (submitMutation.isPending) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh]">
        <div className="w-8 h-8 rounded-full border-2 border-[#c0392b] border-t-transparent animate-spin mb-4" />
        <div className="text-[10px] text-[#c0392b] tracking-widest uppercase">Scoring Quiz...</div>
      </div>
    );
  }

  const progress = ((currentIdx) / quizData.questions.length) * 100;

  return (
    <div className="max-w-3xl mx-auto w-full pt-10">
      {/* Progress Bar */}
      <div className="mb-10">
        <div className="flex justify-between text-[10px] uppercase tracking-widest text-[#666] mb-2">
          <span>Question {currentIdx + 1} of {quizData.questions.length}</span>
          <span>{Math.round(progress)}% Complete</span>
        </div>
        <div className="h-1 bg-white/10 w-full overflow-hidden">
          <motion.div
            className="h-full bg-[#c0392b]"
            initial={{ width: 0 }}
            animate={{ width: `${progress}%` }}
            transition={{ duration: 0.5 }}
          />
        </div>
      </div>

      <AnimatePresence mode="wait">
        <motion.div
          key={q.id}
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: -20 }}
          className="bg-[#080808]/80 backdrop-blur-md p-8 md:p-12 border border-white/10"
        >
          <h2 className="font-serif text-2xl md:text-3xl text-white mb-8 leading-snug">
            {q.question}
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {q.options.map((opt: string, i: number) => {
              const isSelected = lockedIn === i;
              const isLocked = lockedIn !== null;

              return (
                <button
                  key={i}
                  onClick={() => handleSelect(i)}
                  disabled={isLocked}
                  className={`
                    text-left p-4 md:p-6 border transition-all duration-300
                    ${isSelected ? 'bg-[#c0392b] border-[#c0392b] text-white shadow-[0_0_15px_rgba(192,57,43,0.5)]' : 'bg-transparent border-white/10 text-[#d0d0d0] hover:border-white/30 hover:bg-white/5'}
                    ${isLocked && !isSelected ? 'opacity-40 grayscale' : ''}
                  `}
                >
                  <div className="flex items-start gap-4">
                    <span className={`text-[10px] font-mono mt-1 ${isSelected ? 'text-white/80' : 'text-[#c0392b]'}`}>
                      {String.fromCharCode(65 + i)}
                    </span>
                    <span className="text-sm md:text-base leading-tight font-medium">
                      {opt}
                    </span>
                  </div>
                </button>
              );
            })}
          </div>
        </motion.div>
      </AnimatePresence>
    </div>
  );
}

function QuizResultView({
  result,
  onPlayAgain,
}: {
  result: QuizResult;
  onPlayAgain: () => void;
}) {
  return (
    <motion.div
      className="max-w-2xl mx-auto text-center py-10"
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
    >
      <div className="text-[10px] text-[#888] tracking-[0.2em] uppercase mb-4">Quiz Completed</div>
      
      <div className="text-7xl mb-6">{result.tierEmoji}</div>
      
      <div className="font-serif text-5xl md:text-7xl text-[#d4a500] mb-2 font-bold" style={{ textShadow: "0 0 30px rgba(212,165,0,0.3)" }}>
        {result.percentage}%
      </div>
      
      <div className="text-2xl text-white font-medium mb-1">{result.tier}</div>
      <div className="text-[#666] text-sm mb-12">
        You scored {result.totalScore} out of {result.maxScore} points.
      </div>

      <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
        <button
          onClick={onPlayAgain}
          className="w-full sm:w-auto px-8 py-4 text-xs font-bold tracking-[0.15em] uppercase bg-[#c0392b] text-white hover:bg-[#a93226] transition-colors"
        >
          Play Again
        </button>
      </div>

      {/* Breakdown */}
      <div className="mt-16 text-left">
        <h3 className="font-serif text-xl text-white mb-6 border-b border-white/10 pb-2">Match Report</h3>
        <div className="space-y-4">
          {result.breakdown.map((b, i) => (
            <div key={b.questionId} className={`p-4 border ${b.correct ? 'border-green-500/20 bg-green-500/5' : 'border-red-500/20 bg-red-500/5'}`}>
              <div className="flex justify-between items-center mb-1">
                <span className="text-[10px] uppercase tracking-wider text-[#666]">Question {i + 1}</span>
                <span className={`text-[10px] font-bold uppercase tracking-wider ${b.correct ? 'text-green-500' : 'text-red-500'}`}>
                  {b.correct ? '+10' : '0'} Pts
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </motion.div>
  );
}

export default function Quiz() {
  const [phase, setPhase] = useState<QuizPhase>("intro");
  const [result, setResult] = useState<QuizResult | null>(null);
  
  const { data: quizData, isLoading, error, refetch } = useQuiz();

  const handleStart = () => {
    if (!quizData) refetch();
    setPhase("playing");
  };

  const handleComplete = (res: QuizResult) => {
    setResult(res);
    setPhase("result");
  };

  const handlePlayAgain = () => {
    setResult(null);
    setPhase("intro");
    refetch(); // Fetch fresh questions
  };

  return (
    <div className="relative min-h-screen px-4 md:px-8 pb-20">
      <VideoBackground
        src="/stadium-floodlight.mp4"
        opacity={0.6}
        overlayOpacity={0.4}
        className="fixed"
      />
      <div className="absolute inset-0 z-0 bg-gradient-to-b from-transparent via-[#050505]/60 to-[#050505] pointer-events-none fixed" />
      
      <div className="relative z-10 w-full h-full pt-10">
        <AnimatePresence mode="wait">
          {phase === "intro" && (
            <QuizIntro key="intro" onStart={handleStart} />
          )}

          {phase === "playing" && isLoading && (
            <motion.div key="loading" className="flex flex-col items-center justify-center min-h-[60vh]">
              <div className="w-12 h-12 rounded-full border-2 border-[#c0392b] border-t-transparent animate-spin mb-6" />
              <div className="text-[10px] text-[#c0392b] tracking-[0.2em] uppercase font-bold animate-pulse">
                Generating Questions...
              </div>
            </motion.div>
          )}

          {phase === "playing" && error && (
            <motion.div key="error" className="flex flex-col items-center justify-center min-h-[60vh] text-center">
              <div className="text-red-500 mb-4 text-4xl">⚠️</div>
              <h2 className="text-xl text-white mb-2">Arena Unavailable</h2>
              <p className="text-[#888] text-sm mb-6 max-w-sm">
                The quiz generator is currently down. Please try again later.
              </p>
              <button
                onClick={() => setPhase("intro")}
                className="px-6 py-2 border border-white/20 text-xs uppercase tracking-widest hover:bg-white/10"
              >
                Go Back
              </button>
            </motion.div>
          )}

          {phase === "playing" && quizData && (
            <QuizPlay key="playing" quizData={quizData} onComplete={handleComplete} />
          )}

          {phase === "result" && result && (
            <QuizResultView key="result" result={result} onPlayAgain={handlePlayAgain} />
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
