export const driftWallImages = [
  { src: '/gallery/virat 1.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 2.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 3.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 4.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 6.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 7.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 8.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 9.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 10.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 11.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 12.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 13.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 14.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 15.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 16.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 17.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 18.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 19.jpg', alt: 'King Kohli' },
  { src: '/gallery/virat 20.jpg', alt: 'King Kohli' },
];
